jobs:
  terraform-apply:
    name: 'Terraform Apply for Kubernetes and Ingress'
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    #- name: Login to Azure
    #  uses: azure/login@v1
    #  with:
    #    creds: ${{ secrets.AZURE_CREDENTIALS }}

    -name: Login to Azure
     uses: Azure/login@v1
     env:
     CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
     with:
     creds: ${{ env.CREDENTIALS }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    # Apply Terraform in kubernetes directory
    - name: Terraform Init (Kubernetes)
      working-directory: ./kubernetes  # Navigate to the kubernetes project folder
      run: terraform init

    - name: Terraform plan (Kubernetes)
      working-directory: ./kubernetes  # Navigate to the kubernetes project folder
      run: terraform plan
      env:
        TF_VAR_mysql_server_admin_password: ${{ secrets.MYSQL_SERVER_ADMIN_PASSWORD }}

    - name: Terraform Apply (Kubernetes)
      working-directory: ./kubernetes  # Ensure the apply is in the kubernetes project folder
      run: terraform apply -auto-approve

    # Apply Terraform in ingress directory
    - name: Terraform Init (Ingress)
      working-directory: ./ingress  # Navigate to the ingress project folder
      run: terraform init
      env:
        TF_VAR_mysql_server_admin_password: ${{ secrets.MYSQL_SERVER_ADMIN_PASSWORD }}

    - name: Terraform plan (Ingress)
      working-directory: ./ingress  # Navigate to the ingress project folder
      run: terraform plan
      env:
        TF_VAR_mysql_server_admin_password: ${{ secrets.MYSQL_SERVER_ADMIN_PASSWORD }}
    - name: Terraform Apply (Ingress)
      working-directory: ./ingress  # Ensure the apply is in the ingress project folder
      run: terraform apply -auto-approve
      env:
        TF_VAR_mysql_server_admin_password: ${{ secrets.MYSQL_SERVER_ADMIN_PASSWORD }}
